name: medication_management
description: A digital tool for calculating doses in hospital practice and quality of care.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^4.0.0  # For playing alert sounds
  shared_preferences: ^2.1.0  # For local storage
  cupertino_icons: ^1.0.2
  intl: ^0.19.0 # For formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # For app icon generation

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon.jpg" # Path to your app icon